;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname Vijayanand-U-hw0) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
; Udaya Tejas Vijay Anand
; Username: uvijayanand@wpi.edu

;; Question - 1 (a)
(* (- (* 5 3) 
           (- 8 (string-length (string-append "CS" 
                                              "1101"))))
        (/ 48 16))
;; Solution - Question - 1 (a)
     ;(* (- (* 5 3)(- 8 (string-length (string-append "CS" "1101"))))(/ 48 16))
     ;(* (- (* 5 3)(- 8 (string-length (string-append "CS" "1101"))))(3))
     ;(* (- (* 5 3)(- 8 (string-length ("CS1101"))))(3))
     ;(* (- (* 5 3)(- 8 6)))(3))
     ;(* (- (* 5 3) 2))(3))
     ;(* (- 15 2))(3))
     ;(* 13(3))
     ;39
     ;SOLUTION = 39

;; Question - 1 (b)
(define (cube n)
   (* n n n))
(if (> (cube 2) (cube (/ 12 4))) 
         (- 105 107) (sqrt (+ 1 (* 5 3))))
;; Solution - Question - 1 (b)
     ;(if (> (cube 2) (cube (/ 12 4))) (- 105 107) (sqrt (+ 1 (* 5 3))))
     ;(if (> (cube 2) (cube (/ 12 4))) (- 105 107) (sqrt (+ 1 (15))))
     ;(if (> (cube 2) (cube (/ 12 4))) (- 105 107) (sqrt (16)))
     ;(if (> (cube 2) (cube (/ 12 4))) (-2) (4)))
     ;(if (> (8) (cube (3)) (-2) 4)))
     ;(if (> (8) (27) (-2) (4)))
     ;(2 > 27) --> #False
     ;since the value is false "(-2)" will not get executed
     ;4

;-----------------------------------------------------------------------
;Solution - Question - 2

; Image --> Image
;Purpose: The purpose of the code is to consume an image and produces an 
;image that consists of 4 copies of the original image

(require 2htdp/image)

(define (kalediscope Image) (above (beside (flip-horizontal Image) Image)
            (beside (flip-horizontal (flip-vertical Image)) (flip-vertical Image))))

;-----------------------------------------------------------------------

;Solution - Question-3

;Constants Defined:
(define Fixed-Cost 100)

;Income
;     NUMBER --> NUMBER
;Purpose: To consume the input of the number attending adding along the
;fixed cost to conduct the tour
(define (expenses number-of-person)
  (+ Fixed-Cost (* number-of-person 2)))
(check-expect (expenses 20) 140)
(check-expect (expenses 0) 100)
(check-expect (expenses 10) 120)

;Expense
;     NUMBER --> NUMBER
;To consume the total number of people attending and the price per ticket
;and output the income generated by ticket sales
(define (income number-of-person price-per-ticket)
  (* price-per-ticket number-of-person))
(check-expect (income 20 20) 400)
(check-expect (income 0 0) 0)
(check-expect (income 10 10) 100)

;Proceeds
;     NUMBER --> NUMBER
;To consume the total number of people attending and the price per ticket
;and using the helper function, the price of prceeds are known
(define (proceeds number-of-person price-per-ticket)
  (-(income number-of-person price-per-ticket)
  (expenses number-of-person)))
(check-expect (proceeds 20 20) 260)
(check-expect (proceeds 0 0) -100)
(check-expect (proceeds 0 5) -100)
(check-expect (proceeds 5 0) -110)

;-----------------------------------------------------------------------

;Solution - Question - 4

;Constants Defined:
(define Bank-Fees 3000)
(define Interest-Rate 1.04)
(define Loan-Period 15)

;     NUMBER --> NUMBER
;To consume the purchase price and downpayment which outputs the principal
(define (principal purchase-price downpayment)
  (- purchase-price downpayment))
(check-expect (principal 20 10) 10)
(check-expect (principal 20 0) 20)
(check-expect (principal 0 10) -10)
(check-expect (principal 0 0) 0)

;     NUMBER --> NUMBER
;To consume the purchase price and the downpayment to output the interest
(define (interest purchase-price downpayment)
  (* (principal purchase-price downpayment) Interest-Rate Loan-Period))
(check-expect (interest 20 10) 156)
(check-expect (interest 20 0) 312)
(check-expect (interest 0 10) -156)
(check-expect (interest 0 0) 0)

;     NUMBER --> NUMBER
;To consume the purchase price and the downpayment to output the total
;cost of the house
(define (total-cost-of-house purchase-price downpayment)
  (+ purchase-price Bank-Fees (interest purchase-price downpayment)))
(check-expect (total-cost-of-house 20 10) 3176)
(check-expect (total-cost-of-house 20 0) 3332)
(check-expect (total-cost-of-house 0 10) 2844)
(check-expect (total-cost-of-house 0 0) 3000)

;-----------------------------------------------------------------------