# Author: Udaya Vijay Anand

# Define the main target, which produces an executable called 'project2'
project: project2.c student2.c student2_common.c student2A.c student2B.c
	gcc -o project2 project2.c student2.c student2_common.c student2A.c student2B.c -I.

# Define a 'clean' target, which removes the 'project2' executable
clean:
	rm -f project2
